spring:
  profiles:
    active: local
#MongoDB Connection Properties
mongo.uri: "localhost:27017"
mongo.database: "myRetail"
#Product service params
product.description.url: "https://redsky.target.com/v2/pdp/tcin"
product.description.exclusion: "taxonomy,price,promotion,bulk_ship,rating_and_review_reviews,rating_and_review_statistics,question_answer_statistics"
#Async thread params
taskExecutor:
  corepool.size: 64
  maxpool.size: 128
  queue.size: 10000
#Task size
sublist.size: 2
